### ISSUE TITLE
keeping images and content together

### ISSUE THREAD

**Issue by gour** [htkoca/theme-hugo-foundation6#17]
Hello,

I know that the the feature to keep images and content together is still planned to be coded properly for Hugo-1.0, but, atm, it's possible to use it by having the following layout:

```
...
├── config.toml
├── content
│   └── blog
│       ├── posts-1
│       │   └── image-for-post-1.jpg
│       ├── post-1.org
│       └── post-2.org
...
```

In the post I use the following shortcode:

```
{{< figure src="image-for-post-1.jpg" title="Title for post-1 image" >}}

```

but the image is not rendered, while the generated source code looks like this:

```
<figure >
    
        <img src="post-1.jpg" />
    
    
    <figcaption>
        <h4>Title for post-1 image</h4>
        
    </figcaption>
    
</figure>

```

However if I e.g. use:

```
theme = "hugo-theme-bootstrap4-blog"
```

everything is fine.

Any idea?

I'm just starting with Hugo and both Foundation as well as Bootstrap frameworks are new to me and I'm ready to learn, but would like to use Foundation framework since it looks less opinionated and/or easier to customize...

**Comment by htkoca** [comment]
Hugo does not support asset folders & permalink structure does not affect asset folders present as a result (or so I understand, correct me if I'm wrong).

https://github.com/spf13/hugo/issues/1768

Using this permalink settings in `config.toml`:
```
post = "/:title/"
```
may be a hacky workaround to place your rendered post html files in the same folder as the asset ones. 

For further information see @gima's post in the above link in particular.

**Comment by gour** [comment]
> Hugo does not support asset folders & permalink structure does not affect asset folders present as a result (or so I understand, correct me if I'm wrong).

Well, Hugo can detect assets since [0.14](https://github.com/spf13/hugo/releases/tag/v0.14):

* Support for all file types in content directory.

    * If dedicated file type handler isn’t found it will be copied to the destination.

if one has layout as described in my original post above.

With this simple config:

```
languageCode = "en-us"
title = "atmarama.net (Hugo)"
baseURL = "http://example.com/"
#theme = "hugo-theme-foundation6-blog"
theme = "hugo-theme-bootstrap4-blog"
```

I can reference images as mentioned above, so the problem is with the theme itself.

**Comment by htkoca** [comment]
Hmm I'll take a look at it in several hours, I don't have access to my computer at the moment. 

I do want to clarify this though, for replication purposes:

```
├── content
│   └── blog
│       ├── post-1
│       │   └── image-for-post-1.jpg
│       ├── post-1.org
```

What is `.org`? I assume that is supposed to be `.md`?

**Comment by gour** [comment]
> What is .org? I assume that is supposed to be .md?

I'm playing with Hugo's support to use Emacs' org-mode markup when writing content...

**Comment by htkoca** [comment]
Build results using exampleSite config / content from both themes (with `test.md` addition):

[Bootstrap theme test build](http://imgur.com/a/7wjSI)
[Foundation theme test build](http://imgur.com/a/e2KPM)

`test.md` content:

```Markdown
---
author: "Michael Henderson"
date: 2014-09-28
linktitle: test
menu:
  main:
    parent: tutorials
next: /tutorials/github-pages-blog
prev: /tutorials/automated-deployments
title: test
weight: 10
---


## Introduction

...

{{< figure src="unnamed.png" title="Title for post-1 image" >}}

...
```

Seems like Hugo ***is*** copying the assets, ***but*** to their own dedicated folder outside of `test.html`'s folder (`post/test/unnamed.png` vs expected `2014/09/test/unnamed.png`). 

`post = "/post/:title/"` would be the corrected workaround permalink. I know this isn't what you're looking for, but I'm somewhat stuck on this as well. Perhaps, making a custom `figure` shortcode that passes Hugo's `.Permalink` and `.RelPermalink` url path variables (or another variable combination) will allow the IMG to load. Right now, its looking for `2014/09/test/unnamed.png` which doesn't exist.

I've been trying to find a solution for dedicated asset folders within Hugo for some time. Perhaps if we can figure this out it will benefit us both.. ! Meanwhile, I've personally moved onto [Hexo](https://hexo.io/docs/asset-folders.html) because it supports asset folders.

**Comment by htkoca** [comment]
Alternatively, you can place assets like this `static/2014/09/test/unnamed.png`, which isn't ideal but should copy the assets directly into the post's folder.

If you find out what is happening in your `bootstrap4` build that enables this behaviour, I'd be happy to add it to this repository!

**Comment by gour** [comment]
> Meanwhile, I've personally moved onto Hexo because it supports asset folders.

I'm also playing with [Nikola](https://getnikola.com/) where this feature is very straightforward and even [configurable](https://getnikola.com/handbook.html) via `IMAGE_FOLDERS` setting.

**Comment by htkoca** [comment]
I'm closing this issue - Hugo issue at heart
